name: karim_nagar
description: Karim Nagar Society Management Portal
version: 1.0.28+28

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  package_info_plus: ^4.2.0

  # PDF generation
  pdf: ^3.10.4
  printing: ^5.11.1

  # Notifications
  flutter_local_notifications: ^16.3.3
  timezone: ^0.9.2

  url_launcher: ^6.2.4

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
